//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcUrunTakip.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdmin
    {
        public int Admin_Id { get; set; }
        public string Admin_Kullanici_Ad { get; set; }
        public string Admin_Sifre { get; set; }
    }
}
