//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcUrunTakip.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMusteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMusteri()
        {
            this.tblSatislars = new HashSet<tblSatislar>();
        }
    
        public int Musteri_Id { get; set; }
        public string Musteri_Ad { get; set; }
        public string Musteri_Soyad { get; set; }
        public string Musteri_Sehir { get; set; }
        public Nullable<decimal> Musteri_Bakiye { get; set; }
        public Nullable<bool> Musteri_Durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSatislar> tblSatislars { get; set; }
    }
}
