//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcUrunTakip.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSatislar
    {
        public int Satis_Id { get; set; }
        public Nullable<int> Satis_Urun { get; set; }
        public Nullable<int> Satis_Personel { get; set; }
        public Nullable<decimal> Satis_Fiyat { get; set; }
        public Nullable<System.DateTime> Satis_Tarih { get; set; }
        public Nullable<int> Satıs_Musteri { get; set; }
    
        public virtual tblMusteri tblMusteri { get; set; }
        public virtual tblPersonel tblPersonel { get; set; }
        public virtual tblUrun tblUrun { get; set; }
    }
}
