//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcUrunTakip.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUrun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUrun()
        {
            this.tblSatislars = new HashSet<tblSatislar>();
        }
    
        public int Urun_Id { get; set; }
        public string Urun_Ad { get; set; }
        public string Urun_Marka { get; set; }
        public Nullable<short> Urun_Stok { get; set; }
        public Nullable<decimal> Urun_AlisFiyat { get; set; }
        public Nullable<decimal> Urun_SatisFiyat { get; set; }
        public Nullable<int> Kategori { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual tblKategori tblKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSatislar> tblSatislars { get; set; }
    }
}
